name: C++ CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ${{ github.workspace }}/build

    steps:
    - name: Checkout Repository # Download the repository code.
      uses: actions/checkout@v4

    - name: Configure CMake # Generate cross-platform build files.
      run: cmake -S ${{ github.workspace }} -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=Release
      # -S: Assign the current directory to the source file.
      # -B: Create the build directory and output configuration files there.
      # -DCMAKE_BUILD_TYPE=Release: Ensure we compile with -O3 optimization.

    - name: Build # Build the source code.
      run: cmake --build ${{ env.BUILD_DIR }} --parallel
      # --build: Automatically invoke the underlying build tool (make/ninja/msbuild)
      # --parallel: Utilize all available CPU cores to accelerate the build.

    - name: Run Unit Tests
      working-directory: ${{ env.BUILD_DIR }}
      run: ctest --output-on-failure
      # --output-on-failure: Print detailed logs if the tests failed.

    - name: Run Benchmarks
      if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
      working-directory: ${{ env.BUILD_DIR }}
      run: ./bin/mcr_benchmark